all: html

SPHINX_PROJECT_NAME = Analogue to Digital Conversion (ADC) Test Harness Application Quickstart Guide
VERSION = 0.1
SOURCE_INCLUDE_DIRS = ../../app_test_adc/src
XDOC_DIR ?= ../../../../xdoc
include $(XDOC_DIR)/Makefile.inc
