all: html

SPHINX_PROJECT_NAME = Hall Sensor Test Harness Application Quickstart Guide
VERSION = 0.1
SOURCE_INCLUDE_DIRS = ../../app_test_hall
XDOC_DIR ?= ../../../../xdoc
include $(XDOC_DIR)/Makefile.inc
