SPHINX_PROJECT_NAME=xSOFTip FOC Motor Control QEI Library
VERSION=1.0
DOXYGEN_DIRS=../../../sw_foc_motor_control/module_foc_qei/src 
SOURCE_INCLUDE_DIRS=../../../sw_foc_motor_control/module_foc_qei/src 
XDOC_DIR ?= ../../../xdoc
include $(XDOC_DIR)/Makefile.inc
