SPHINX_PROJECT_NAME=xSOFTip FOC Motor Control PWM Library
VERSION=1.0
DOXYGEN_DIRS=../../../sw_foc_motor_control/module_foc_pwm
SOURCE_INCLUDE_DIRS=../../../sw_foc_motor_control
XDOC_DIR ?= ../../../xdoc
include $(XDOC_DIR)/Makefile.inc
